function D=Denavit(ang,d,a,alpha)
D=[cosd(ang) -sind(ang)*cosd(alpha) sind(alpha)*sind(ang) a*cosd(ang);...
   sind(ang) cosd(ang)*cosd(alpha) -cosd(ang)*sind(alpha) a*sind(ang);...
   0           sind(alpha)                    cosd(alpha)             d;...
   0                0                              0                      1;];
end